services:
  - type: web
    name: contentaiboost
    env: node
    plan: free
    buildCommand: |
      cd client
      npm install
      npm run build
      cd ..
      npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 